version: "3"

services:
  node-app:
    build: .
    container_name: node-app
    image: node-app-image
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
      
    env_file:
      - ./.env
