version: "3"

services:
  node-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=thabiso
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
    command: mongod --bind_ip_all
    restart: unless-stopped
    ports:
      - "27017:27017"
  
  redis:
    image: redis

volumes:
  mongo-db:
